<?php
/**
 * Created by PhpStorm.
 * User: admindyn
 * Date: 2017/1/18
 * Time: 下午3:00
 */

namespace OBJECTPHP;


class DianShi
{
    public $yanse;
    public $pinPai;

    function  __construct()
    {
        //构造函数
    }


    function  kan()
    {
        echo '看电视';
    }

    function __destruct()
    {
        // TODO: Implement __destruct() method.
        //析构函数

    }

}

/*
 * 对象的内存释放
 *
 * 对象的析构函数 对象生命周期
 *
 * 内存回收 第一种情况 php系统回收 用户关闭页面
 *
 * 通过unset 删除引用 来释放对象（这里需要注意 当一个实例对象被多个变量引用时  需要全部unset 内存才能被正确释放）
 *
 *-------
 * 封装 把成员方法 成员属性封装到类中
 * 隐藏属性和方法 隐藏方法实现的细节
 * 通过 public
 * protected
 * private
 * final
 * static 限定类成员的访问权限
 *
 * 数据被保护在内部
 *
 * 只有通过被授权的成员方法
 *
 * 才可以操作
 *
 * -------
 * 继承 可以使一个类继承并拥有另一个已经存在的类的
 * 成员属性和方法
 * 被继承的类为父类 或  基类
 *
 * 继承类为 子类 extends 关键字实现继承关系
 *
 *
 * */

class  Arc1{
    function del($id)
    {
        echo '</br>'.'删除文章1';
    }
}

class ArcNew extends Arc1 {

    function del($id)
    {
        parent::del($id); // TODO: Change the autogenerated stub

        /*
         * 这里 子类继承 父类 发现父类的 方法 不能满足子类的方法诉求
         *
         * 因此对该方法 重写 但是 其改变并不影响父类 只是自己类对应影响
         * */

        echo '</br>'.'删除文章2';
    }
}

/*
 * php 不能继承多次 单继承的 但是PHP可以做到  单继承 多实现
 * */

$arc = new ArcNew();

$arc->del('sss');


/*
 *
 *
 *
 * php 不能做到像 java 中的多态
 *
 * 但是要明白 多态 实现的 基础是 先有继承
 *
 * 多态： 子类 继承 父类 通过对父类的方法重写实现多态
 *
 * 但是在OC Java中的多态 是通过 数据类型来做到的
 *
 * 比如继承的方法 传参 类型为 NSObject类型 但是传入却是各种该类型的继承类
 *
 * 进一步做到多态
 *
 * */












